# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# MongoDB Atlas Configuration
# ===============================

# ===============================
# Jackson (JSON)
# ===============================
spring.jackson.serialization.indent_output=true

# ===============================
# Logging (Mongo Queries dekhne ke liye)
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

# ===============================
# Spring Boot App Name
# ===============================
spring.application.name=spring-mongo-backend

# ===============================
# Error Handling
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
spring.profiles.active=${ENV:dev}


